# Generated by Django 2.0.10 on 2019-01-17 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('FilmId', models.CharField(auto_created=True, max_length=255, primary_key=True, serialize=False)),
                ('FilmName', models.CharField(max_length=255)),
                ('Genre', models.CharField(max_length=255)),
                ('Studio', models.CharField(max_length=255)),
                ('Director', models.CharField(max_length=255)),
                ('Producer', models.CharField(max_length=255)),
                ('LeadActor', models.CharField(max_length=255)),
            ],
        ),
    ]
